# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    background: gray;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.port_selection_frame = QtWidgets.QFrame(self.centralwidget)
        self.port_selection_frame.setStyleSheet("#port_selection_frame {\n"
"    border: 1px solid black;\n"
"    background: white;\n"
"}")
        self.port_selection_frame.setObjectName("port_selection_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.port_selection_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.com_port_selection_frame = QtWidgets.QFrame(self.port_selection_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.com_port_selection_frame.sizePolicy().hasHeightForWidth())
        self.com_port_selection_frame.setSizePolicy(sizePolicy)
        self.com_port_selection_frame.setStyleSheet(".QFrame{\n"
"    border: 1px solid black;\n"
"}")
        self.com_port_selection_frame.setObjectName("com_port_selection_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.com_port_selection_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.port_selector_label = QtWidgets.QLabel(self.com_port_selection_frame)
        self.port_selector_label.setObjectName("port_selector_label")
        self.horizontalLayout_6.addWidget(self.port_selector_label)
        self.port_list = QtWidgets.QComboBox(self.com_port_selection_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_list.sizePolicy().hasHeightForWidth())
        self.port_list.setSizePolicy(sizePolicy)
        self.port_list.setEditable(False)
        self.port_list.setMaxVisibleItems(5)
        self.port_list.setObjectName("port_list")
        self.port_list.addItem("")
        self.horizontalLayout_6.addWidget(self.port_list)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.com_port_selection_frame)
        self.label_3 = QtWidgets.QLabel(self.port_selection_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.port_selection_frame)
        self.privileged_exec_mode_frame = QtWidgets.QFrame(self.centralwidget)
        self.privileged_exec_mode_frame.setStyleSheet("#privileged_exec_mode_frame {\n"
"    border: 1px solid black;\n"
"    background: white;\n"
"}")
        self.privileged_exec_mode_frame.setObjectName("privileged_exec_mode_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.privileged_exec_mode_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.reset_privileged_exec_mode_frame = QtWidgets.QFrame(self.privileged_exec_mode_frame)
        self.reset_privileged_exec_mode_frame.setStyleSheet(".QFrame{\n"
"    border: 1px solid black;\n"
"}")
        self.reset_privileged_exec_mode_frame.setObjectName("reset_privileged_exec_mode_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.reset_privileged_exec_mode_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.privileged_exec_mode_password_label = QtWidgets.QLabel(self.reset_privileged_exec_mode_frame)
        self.privileged_exec_mode_password_label.setObjectName("privileged_exec_mode_password_label")
        self.horizontalLayout.addWidget(self.privileged_exec_mode_password_label)
        self.reset_privileged_exec_mode_toggle = QtWidgets.QRadioButton(self.reset_privileged_exec_mode_frame)
        self.reset_privileged_exec_mode_toggle.setText("")
        self.reset_privileged_exec_mode_toggle.setObjectName("reset_privileged_exec_mode_toggle")
        self.horizontalLayout.addWidget(self.reset_privileged_exec_mode_toggle, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.reset_privileged_exec_mode_frame)
        self.new_privileged_exec_mode_password_frame = QtWidgets.QFrame(self.privileged_exec_mode_frame)
        self.new_privileged_exec_mode_password_frame.setStyleSheet(".QFrame{\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.new_privileged_exec_mode_password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_privileged_exec_mode_password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_privileged_exec_mode_password_frame.setObjectName("new_privileged_exec_mode_password_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.new_privileged_exec_mode_password_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.new_privileged_exec_mode_password_frame)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.set_new_privileged_exec_mode_password_toggle = QtWidgets.QRadioButton(self.new_privileged_exec_mode_password_frame)
        self.set_new_privileged_exec_mode_password_toggle.setText("")
        self.set_new_privileged_exec_mode_password_toggle.setObjectName("set_new_privileged_exec_mode_password_toggle")
        self.horizontalLayout_2.addWidget(self.set_new_privileged_exec_mode_password_toggle, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.new_privileged_exec_mode_password_frame)
        self.privileged_exec_mode_password_input = QtWidgets.QLineEdit(self.privileged_exec_mode_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.privileged_exec_mode_password_input.sizePolicy().hasHeightForWidth())
        self.privileged_exec_mode_password_input.setSizePolicy(sizePolicy)
        self.privileged_exec_mode_password_input.setStyleSheet("border: 1px solid black")
        self.privileged_exec_mode_password_input.setText("")
        self.privileged_exec_mode_password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.privileged_exec_mode_password_input.setObjectName("privileged_exec_mode_password_input")
        self.verticalLayout_2.addWidget(self.privileged_exec_mode_password_input)
        self.frame = QtWidgets.QFrame(self.privileged_exec_mode_frame)
        self.frame.setStyleSheet(".QFrame {\n"
"    border: 1px solid black;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.encrypt_label = QtWidgets.QLabel(self.frame)
        self.encrypt_label.setObjectName("encrypt_label")
        self.horizontalLayout_3.addWidget(self.encrypt_label)
        self.encrypt_privileged_exec_mode_password_toggle = QtWidgets.QRadioButton(self.frame)
        self.encrypt_privileged_exec_mode_password_toggle.setText("")
        self.encrypt_privileged_exec_mode_password_toggle.setObjectName("encrypt_privileged_exec_mode_password_toggle")
        self.horizontalLayout_3.addWidget(self.encrypt_privileged_exec_mode_password_toggle, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.privileged_exec_mode_frame)
        self.line_console_frame = QtWidgets.QFrame(self.centralwidget)
        self.line_console_frame.setStyleSheet(" #line_console_frame {\n"
"    border: 1px solid black;\n"
"    background: white;\n"
"}")
        self.line_console_frame.setObjectName("line_console_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.line_console_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.reset_line_console_password_frame = QtWidgets.QFrame(self.line_console_frame)
        self.reset_line_console_password_frame.setStyleSheet(".QFrame{\n"
"    border: 1px solid black;\n"
"}")
        self.reset_line_console_password_frame.setObjectName("reset_line_console_password_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.reset_line_console_password_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line_console_password_label = QtWidgets.QLabel(self.reset_line_console_password_frame)
        self.line_console_password_label.setObjectName("line_console_password_label")
        self.horizontalLayout_4.addWidget(self.line_console_password_label)
        self.reset_line_console_password_toggle = QtWidgets.QRadioButton(self.reset_line_console_password_frame)
        self.reset_line_console_password_toggle.setText("")
        self.reset_line_console_password_toggle.setObjectName("reset_line_console_password_toggle")
        self.horizontalLayout_4.addWidget(self.reset_line_console_password_toggle, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.reset_line_console_password_frame)
        self.new_line_console_password_frame = QtWidgets.QFrame(self.line_console_frame)
        self.new_line_console_password_frame.setStyleSheet(".QFrame{\n"
"    border: 1px solid black;\n"
"}")
        self.new_line_console_password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_line_console_password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_line_console_password_frame.setObjectName("new_line_console_password_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.new_line_console_password_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.new_line_console_password_frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.new_line_console_password_toggle = QtWidgets.QRadioButton(self.new_line_console_password_frame)
        self.new_line_console_password_toggle.setText("")
        self.new_line_console_password_toggle.setObjectName("new_line_console_password_toggle")
        self.horizontalLayout_7.addWidget(self.new_line_console_password_toggle, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.new_line_console_password_frame)
        self.line_console_password_input = QtWidgets.QLineEdit(self.line_console_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_console_password_input.sizePolicy().hasHeightForWidth())
        self.line_console_password_input.setSizePolicy(sizePolicy)
        self.line_console_password_input.setStyleSheet("border: 1px solid black")
        self.line_console_password_input.setText("")
        self.line_console_password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_console_password_input.setObjectName("line_console_password_input")
        self.verticalLayout_3.addWidget(self.line_console_password_input)
        self.verticalLayout.addWidget(self.line_console_frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.confirm_frame = QtWidgets.QFrame(self.centralwidget)
        self.confirm_frame.setStyleSheet(".QFrame{\n"
"    border: 1px solid black;\n"
"    background: white;\n"
"}")
        self.confirm_frame.setObjectName("confirm_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.confirm_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.confirm_button = QtWidgets.QPushButton(self.confirm_frame)
        self.confirm_button.setObjectName("confirm_button")
        self.horizontalLayout_5.addWidget(self.confirm_button, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.confirm_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.port_list.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.port_selector_label.setText(_translate("MainWindow", "Please select  a COM port:"))
        self.port_list.setCurrentText(_translate("MainWindow", "None"))
        self.port_list.setItemText(0, _translate("MainWindow", "None"))
        self.label_3.setText(_translate("MainWindow", "Select passwords to reset:"))
        self.privileged_exec_mode_password_label.setText(_translate("MainWindow", "Remove privileged exec mode password"))
        self.label.setText(_translate("MainWindow", "Set new privileged exec mode password"))
        self.privileged_exec_mode_password_input.setPlaceholderText(_translate("MainWindow", "New privileged Exec mode password"))
        self.encrypt_label.setText(_translate("MainWindow", "Encrypt"))
        self.line_console_password_label.setText(_translate("MainWindow", "Remove line console password"))
        self.label_2.setText(_translate("MainWindow", "Set new line console password"))
        self.line_console_password_input.setPlaceholderText(_translate("MainWindow", "New line console password"))
        self.confirm_button.setText(_translate("MainWindow", "Start"))
